version: "3.7"

services:
    backend:
        build: ./backend
        ports:
        - "5000:5000"
        environment:
        - MONGO_INITDB_ROOT_PASSWORD=example_password
    frontend:
        build: ./frontend
        ports:
        - "3000:3000"